name: Deploy to Production Server

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: azure
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        token: ${{ secrets.GH_TOKEN }}

    - name: Build and Run Docker
      run: |
        docker-compose build
        docker-compose down
        docker-compose up -d
